services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: strapi-dev
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_pass
      NODE_ENV: development
    volumes:
      - ./your-strapi-app:/app
      - /app/node_modules        # Avoid overwriting node_modules in container
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - dev-net

  postgres:
    image: postgres:15
    container_name: strapi-db-dev
    environment:
      POSTGRES_DB: strapi_db
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-net

  nginx:
    image: nginx:latest
    container_name: strapi-nginx-dev
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - strapi
    networks:
      - dev-net

volumes:
  pgdata:

networks:
  dev-net:
    driver: bridge
